# docker-compose.yml
version: "3.9"
services:
  postgres:
    build:
      context: .
    ports:
      - "55432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=memories
      - PGDATA=/var/lib/postgresql/data/pgdata